### ISSUE TITLE
Updated release?

### ISSUE THREAD

**Issue by xJon** [SpitefulFox/LostMagic#5]
Hi! Any chance for an updated release, which includes https://github.com/SpitefulFox/LostMagic/commit/ab92680b71c69e2f018bc725a129211ae3b4c33a?
Thanks!

**Comment by jeremydiamondnyfa** [comment]
Did I not release it like that?  That's so weird.  Does removing that tag fix things?

**Comment by xJon** [comment]
@jeremydiamondnyfa Yeah it doesn't include that change, and yes according to https://www.reddit.com/r/Thaumcraft/comments/w28jc8/lost_magic_not_working/

**Comment by SpitefulFox** [comment]
Oof.  Has this been just broken like this the entire time?  Yikes?  I'll go ahead and make a new release.  Thanks for bringing it to my attention.
