### ISSUE TITLE
Updating 1.12.2 Perfectly Complex pack to version 1.5.3 causes issues

### ISSUE THREAD

**Issue by linkbeta5** [SpitefulFox/LostMagic#6]
The 1.12.2 Perfectly Complex pack was updated today to version 1.5.3 and had updated LostMagic when it had done so. The Apocrypha tab of the Thaumnomicon had changed quite a bit, including the first part of its research called "Lost Magic". According to it, I have everything needed to complete the research but when I press "complete", nothing happens. 
![image](https://user-images.githubusercontent.com/125415804/229018449-e7112cb3-73d0-498d-8692-60fced000b06.png)

**Comment by xJon** [comment]
For reference the previous modpack version ran Lost Magic `1.0.2` whereas the latest modpack version uses `1.0.3`.

**Comment by SpitefulFox** [comment]
You sure the pack isn't doing something weird like tweaking researches?  That localization text doesn't match anything that should be showing up in the mod.  Forbidden Magic is the old 1.7.10 mod.

**Comment by xJon** [comment]
@SpitefulFox No tweaked researches although now that you mention it [ReForbidden Magic](https://www.curseforge.com/minecraft/mc-mods/reforbidden-magic) has been added to this version (with claimed compatibility with Lost Magic). @KELETU66666 any idea what's happening here?

**Comment by S-Leader** [comment]
hmmm, yeah, i change it
bacause it's buggy when i make "ReForbiddenMagic" mod, so i added this research page.

**Comment by xJon** [comment]
@KELETU66666 I don't perfectly understand what you mean (did you setup Lost Magic research under/within ReForbidden Magic?) but regardless I assume this is a ReForbidden Magic issue rather than a Lost Magic issue.

**Comment by S-Leader** [comment]
> @KELETU66666 I don't perfectly understand what you mean (did you setup Lost Magic research under/within ReForbidden Magic?) but regardless I assume this is a ReForbidden Magic issue rather than a Lost Magic issue.

ReForbbidenMagic Need LostMagic to it's front
